#!/bin/sh
set -e

case "$1" in
  remove|upgrade)
    if [ -x /bin/systemctl ]; then
      systemctl stop laps-server.service >/dev/null 2>&1 || true
      systemctl disable laps-server.service >/dev/null 2>&1 || true
    fi
    ;;
esac

exit 0
